<a href="https://colab.research.google.com/github/pewpiece/Google-Collab/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy coding challange


1. Write a Python program to do the following task.

Use the NumPy library to create an array (say arr) of the first 25 (exclusive) integers starting from 0.

Reshape the array into shape (5, 5).


Select the elements present in first two rows (i.e. row 0 and row 1) and last two columns (i.e. column 3 and column 4)

In [ ]:
import numpy as np


arr = np.arange(25)


arr = arr.reshape((5, 5))

selected = arr[0:2, 3:5]


print("Original 5x5 array:\n", arr)
print("\nSelected elements (first 2 rows, last 2 columns):\n", selected)


Original 5x5 array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Selected elements (first 2 rows, last 2 columns):
 [[3 4]
 [8 9]]


2. From the array created in question 1 (i.e. 5 x 5 array), select all the elements at evenly positioned columns and oddly positioned rows. Use stride concept here.

In [ ]:
import numpy as np

# Create and reshape the array
arr = np.arange(25).reshape((5, 5))

# Use slicing with strides: rows 1 and 3 (start at 1, step 2), columns 0, 2, 4 (start at 0, step 2)
selected = arr[1::2, ::2]

# Print results
print("Original 5x5 array:\n", arr)
print("\nSelected elements (odd rows, even columns):\n", selected)


Original 5x5 array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Selected elements (odd rows, even columns):
 [[ 5  7  9]
 [15 17 19]]


Python List and Numpy array

In [ ]:
# Python list
list1 = [1, 2, 3]
list2 = [4, 5, 6]
print(list1 + list2)  # Concatenates


[1, 2, 3, 4, 5, 6]


Numpy array

In [ ]:
# NumPy array
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)  # Element-wise addition


[5 7 9]


Attributes of an array and creating basic array

In [ ]:
import numpy as np

# 1D array
arr1 = np.array([1, 2, 3, 4])

# 2D array
arr2 = np.array([[1, 2], [3, 4]])


In [ ]:
print("Dimensions:", arr2.ndim)
print("Shape:", arr2.shape)
print("Size:", arr2.size)
print("Data type:", arr2.dtype)
print("Item size:", arr2.itemsize)
print("Total bytes:", arr2.nbytes)


Dimensions: 2
Shape: (2, 2)
Size: 4
Data type: int64
Item size: 8
Total bytes: 32


In [ ]:
np.zeros((2, 3))       # 2x3 array of 0s
np.ones((3, 2))        # 3x2 array of 1s
np.eye(3)              # 3x3 identity matrix
np.arange(0, 10, 2)    # [0, 2, 4, 6, 8]
np.linspace(0, 1, 5)   # 5 evenly spaced numbers between 0 and 1


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Basic methods on array and reshaping
Add, Remove and Sort
Reshaping an Array


In [ ]:
import numpy as np

arr = np.array([1, 2, 3])
new_arr = np.append(arr, [4, 5])
print(new_arr)  # [1 2 3 4 5]


[1 2 3 4 5]


In [ ]:
arr = np.array([1, 2, 3, 4])
new_arr = np.delete(arr, 2)  # Removes element at index 2
print(new_arr)  # [1 2 4]


[1 2 4]


In [ ]:
arr = np.array([3, 1, 4, 2])
sorted_arr = np.sort(arr)
print(sorted_arr)  # [1 2 3 4]


[1 2 3 4]


In [ ]:
arr = np.arange(12)  # [0, 1, ..., 11]
reshaped = arr.reshape((3, 4))  # 3 rows, 4 columns
print(reshaped)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
arr.flatten()      # Converts multi-D array to 1D
arr.T              # Transpose of a 2D array
arr.ravel()        # Similar to flatten (returns view if possible)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Indexing and Slicing
Positive Indexing
Positive Indexing: Exercise - Quiz
Negative Indexing
Negative Indexing: Exercise - Quiz
Striding

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr[0])  # 10
print(arr[2])  # 30


10
30


In [ ]:
print(arr[1:4])  # [20 30 40]
print(arr[:3])   # [10 20 30]
print(arr[2:])   # [30 40 50]


[20 30 40]
[10 20 30]
[30 40 50]


In [ ]:
arr = np.array([100, 200, 300, 400, 500])
print(arr[-1])  # 500
print(arr[-2])  # 400


500
400


In [ ]:
print(arr[-3:-1])  # [300 400]
print(arr[-4:])    # [200 300 400 500]


[300 400]
[200 300 400 500]


In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6])
print(arr[::2])   # [0 2 4 6] (every 2nd element)
print(arr[1::3])  # [1 4] (start at 1, step 3)


[0 2 4 6]
[1 4]
